name: CI Simples

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o código
        uses: actions/checkout@v3

      - name: Rodar um teste de exemplo
        run: echo "Tudo certo com a pipeline!"
